platform :ios, '8.0'

target 'kxtxApp' do
    pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
    pod 'React', path: '../node_modules/react-native/', :subspaces => [
        'jschelpers_legacy',
    ]
    pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end
